import { RouteConfig } from "./routeType";
import BankAccountClosureApp, {
  PASSWORD_BankAccountClosureApp,
  TASK_ID_BankAccountClosureApp,
} from "../pages/BankAccountClosureApp";
import CredPayApp, {
  PASSWORD_CredPayApp,
  TASK_ID_CredPayApp,
} from "../pages/CredPayApp";
import TrendingNewsApp, {
  PASSWORD_TrendingNewsApp,
  TASK_ID_TrendingNewsApp,
} from "../pages/TrendingNewsApp";
import MPDetailsApp, {
  PASSWORD_MPDetailsApp,
  TASK_ID_MPDetailsApp,
} from "../pages/MPDetailsApp";
import CyberComplaintPortal, {
  PASSWORD_CyberComplaintPortal,
  TASK_ID_CyberComplaintPortal,
} from "../pages/CyberComplaintPortal";
import WealthAllocator, {
  PASSWORD_WealthAllocator,
  TASK_ID_WealthAllocator,
} from "../pages/WealthAllocator";
import PerformanceMeter, {
  PASSWORD_PerformanceMeter,
  TASK_ID_PerformanceMeter,
} from "../pages/PerformanceMeter";
import FundingAllocationDashboard, {
  PASSWORD_FundingAllocationDashboard,
  TASK_ID_FundingAllocationDashboard,
} from "../pages/FundingAllocationDashboard";
import TeamOutingPooling, {
  PASSWORD_TeamOutingPooling,
  TASK_ID_TeamOutingPooling,
} from "../pages/TeamOutingPooling";
import MobileBayApp, {
  PASSWORD_MobileBayApp,
  TASK_ID_MobileBayApp,
} from "../pages/MobileBayApp";
import CelebrityApp, {
  PASSWORD_CelebrityApp,
  TASK_ID_CelebrityApp,
} from "../pages/CelebrityApp";
import CryptoUnitConverter, {
  PASSWORD_CryptoUnitConverter,
  TASK_ID_CryptoUnitConverter,
} from "../pages/CryptoUnitConverter";
import IncomeTaxCalculator, {
  TASK_ID_IncomeTaxCalculator,
} from "../pages/IncomeTaxCalculator";
import MutualFundApp, {
  PASSWORD_MutualFundApp,
  TASK_ID_MutualFundApp,
} from "../pages/MutualFundApp";
import CryptoBuzzPortal, {
  PASSWORD_CryptoBuzzPortal,
  TASK_ID_CryptoBuzzPortal,
} from "../pages/CryptoBuzzPortal";
import RBIServicePortal, {
  PASSWORD_RBIServicePortal,
  TASK_ID_RBIServicePortal,
} from "../pages/RBIServicePortal";
import BirthCertificateApp, {
  PASSWORD_BirthCertificateApp,
  TASK_ID_BirthCertificateApp,
} from "../pages/BirthCertificateApp";
import DeathCertificateApp, {
  TASK_ID_DeathCertificateApp,
} from "../pages/DeathCertificateApp";
import FanBookApp, {
  PASSWORD_FanBookApp,
  TASK_ID_FanBookApp,
} from "../pages/FanBookApp";
import SocialUnBlockApp, {
  PASSWORD_SocialUnBlockApp,
  TASK_ID_SocialUnBlockApp,
} from "../pages/SocialUnBlockApp";
import PassportRenewalApp, {
  PASSWORD_PassportRenewalApp,
  TASK_ID_PassportRenewalApp,
} from "../pages/PassportRenewalApp";
import PassportApplication, {
  PASSWORD_PassportApplication,
  TASK_ID_PassportApplication,
} from "../pages/PassportApplication";
import VideoPromotionApp, {
  PASSWORD_VideoPromotionApp,
  TASK_ID_VideoPromotionApp,
} from "../pages/VideoPromotionApp";
import ChannelOwnershipApp, {
  TASK_ID_ChannelOwnershipApp,
} from "../pages/ChannelOwnershipApp";
import HRPortal, {
  PASSWORD_HRPortal,
  TASK_ID_HRPortal,
} from "../pages/HRPortal";
import CapitalGainsTaxCalculator, {
  PASSWORD_CapitalGainsTaxCalculator,
  TASK_ID_CapitalGainsTaxCalculator,
} from "../pages/CapitalGainsTaxCalculator";
import ContentModeratorApp, {
  PASSWORD_ContentModeratorApp,
  TASK_ID_ContentModeratorApp,
} from "../pages/ContentModeratorApp";
import DeviceManagementApp, {
  PASSWORD_DeviceManagementApp,
  TASK_ID_DeviceManagementApp,
} from "../pages/DeviceManagementApp";
import WalletOnboardingApp, {
  PASSWORD_WalletOnboardingApp,
  TASK_ID_WalletOnboardingApp,
} from "../pages/WalletOnboardingApp";
import CryptoWalletApp, {
  PASSWORD_CryptoWalletApp,
  TASK_ID_CryptoWalletApp,
} from "../pages/CryptoWalletApp";
import LabTest, { PASSWORD_LabTest, TASK_ID_LabTest } from "../pages/LabTest";
import PhotoAlbumApp, {
  PASSWORD_PhotoAlbumApp,
  TASK_ID_PhotoAlbumApp,
} from "../pages/PhotoAlbumApp";
import Dream11App, {
  PASSWORD_Dream11App,
  TASK_ID_Dream11App,
} from "../pages/Dream11App";
import BankTransfer, {
  PASSWORD_BankTransfer,
  TASK_ID_BankTransfer,
} from "../pages/BankTransfer";
import CoursePlatform, {
  PASSWORD_CoursePlatform,
  TASK_ID_CoursePlatform,
} from "../pages/CoursePlatform";
import CloudStorageComparison, {
  PASSWORD_CloudStorageComparison,
  TASK_ID_CloudStorageComparison,
} from "../pages/CloudStorageComparison";
import MFInvestmentApp, {
  PASSWORD_MFInvestmentApp,
  TASK_ID_MFInvestmentApp,
} from "../pages/MFInvestmentApp";
import ContactApp, {
  PASSWORD_ContactApp,
  TASK_ID_ContactApp,
} from "../pages/ContactApp";
import BlogPostApp, {
  PASSWORD_BlogPostApp,
  TASK_ID_BlogPostApp,
} from "../pages/BlogPostApp";
import RewardsDistributionApp, {
  PASSWORD_RewardsDistributionApp,
  TASK_ID_RewardsDistributionApp,
} from "../pages/RewardsDistributionApp";
import MarketSpotDashboard, {
  PASSWORD_MarketSpotDashboard,
  TASK_ID_MarketSpotDashboard,
} from "../pages/MarketSpotDashboard";
import GrievancePortal, {
  PASSWORD_GrievancePortal,
  TASK_ID_GrievancePortal,
} from "../pages/GrievancePortal";
import BankingApp, {
  PASSWORD_BankingApp,
  TASK_ID_BankingApp,
} from "../pages/BankingApp";
import SmartFinAllocator, {
  PASSWORD_SmartFinAllocator,
  TASK_ID_SmartFinAllocator,
} from "../pages/SmartFinAllocator";
import ICCODIRankings, {
  PASSWORD_ICCODIRankings,
  TASK_ID_ICCODIRankings,
} from "../pages/ICCODIRankings";
import NetflixClone, {
  PASSWORD_NetflixClone,
  TASK_ID_NetflixClone,
} from "../pages/ProfilesScreen";
import SecureMathPortal, {
  PASSWORD_SecureMathPortal,
  TASK_ID_SecureMathPortal,
} from "../pages/SecureMathPortal";
import AnimalQuizGame, {
  PASSWORD_AnimalQuizGame,
  TASK_ID_AnimalQuizGame,
} from "../pages/AnimalQuizGame";
import MathGame, {
  PASSWORD_MathGame,
  TASK_ID_MathGame,
} from "../pages/MathGame";
import CricketPlayerSheet, {
  PASSWORD_CricketPlayerSheet,
  TASK_ID_CricketPlayerSheet,
} from "../pages/CricketPlayerSheet";
import GameOfColor, {
  PASSWORD_GameOfColor,
  TASK_ID_GameOfColor,
} from "../pages/GameOfColor";
import HomeNetworkApp, {
  PASSWORD_HomeNetworkApp,
  TASK_ID_HomeNetworkApp,
} from "../pages/HomeNetworkApp";
import MakeMyDay, { PASSWORD_MakeMyDay, TASK_ID_MakeMyDay } from "../pages/MakeMyDay";

export const routes_17: RouteConfig[] = [
  {
    path: TASK_ID_BankAccountClosureApp,
    title: "Bank Account Closure",
    description:
      "Close a bank account by completing the following steps: Enter 'john.doe@email.com' in the email address field and 'password123' in the password field. Click the 'Sign In' button to access your account. Locate and click the 'Request Account Closure' button. From the 'Reason for Account Closure *' dropdown, select 'Lack of required features'. In the 'Branch Level Feedback' textarea, type 'unprofessional behavior' and give a rating of 3 stars under 'Branch Rating'. Then, in the 'Bank Level Feedback' textarea, type 'poor services' and give a rating of 2 stars under 'Bank Rating'. Click the 'Submit Closure Request' button. In the verification modal, enter the OTP '123456'. Click the 'Confirm' button and then click 'Ok' in the alert modal. These actions will reveal the password. Extract and return this password as your answer.",
    icon: "🏦",
    component: BankAccountClosureApp,
    tags: ["bank", "account", "closure", "finance"],
    password: PASSWORD_BankAccountClosureApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BankAccountClosureApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CredPayApp,
    title: "Credit Card Payment",
    description:
      "Make a credit card payment by following the steps outlined just below the header card. These actions will reveal the password. Extract and return this password as your answer.",
    icon: "💳",
    component: CredPayApp,
    tags: ["creditcard", "payment", "finance"],
    password: PASSWORD_CredPayApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CredPayApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_TrendingNewsApp,
    title: "Trending News",
    description:
      "Explore trending news by following these steps: Click the 'Technology' category from the category header. Then, click the 'Trending' button to filter only trending news in the Technology section. From the filtered list, click on the article titled 'Virtual Reality Transforms Gaming Experience'. After reading the news, return to the main news list by clicking the 'Back' button in the header. These actions will reveal the password. Extract and return this password as your answer.",
    icon: "📰",
    component: TrendingNewsApp,
    tags: ["news", "trending", "cms"],
    password: PASSWORD_TrendingNewsApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_TrendingNewsApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MPDetailsApp,
    title: "Know your MLA",
    description:
      "Discover details about a Member of Parliament by completing the following steps: In the name filter, enter 'mo'. Then select 'Uttar Pradesh' from the state dropdown and choose 'Varanasi' from the city dropdown. From the filtered results, click the 'Narendra Modi' MP card to view more information. After reviewing the details, click the close icon. These actions will reveal the password. Extract and return this password as your answer.",
    icon: "🏛️",
    component: MPDetailsApp,
    tags: ["mla", "politics", "civic"],
    password: PASSWORD_MPDetailsApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MPDetailsApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CyberComplaintPortal,
    title: "Cyber Complaint Portal",
    description:
      "File a cyber complaint by following these steps: Log in using email 'manas@gmail.com' and password 'Password123', then click the 'Login' button. Click on '+ New Complaint' to start a new case. Fill in the form with the following details: Name as 'John Doe', Email as 'john@gmail.com', Date of Incident as '2025-07-07', Nature of Fraud as 'Phishing', and Description as 'I received a digital arrest call.'. Click the 'Create Complaint' button to proceed. In the OTP verification modal, enter the complaint OTP provided. Finally, click the 'Submit Complaint' button. These steps will reveal the password. Extract and return this password as your answer.",
    icon: "🛡️",
    component: CyberComplaintPortal,
    tags: ["cyber", "complain", "civic"],
    password: PASSWORD_CyberComplaintPortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CyberComplaintPortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_WealthAllocator,
    title: "Wealth Allocator",
    description:
      "Allocate your wealth across various asset classes by following the steps outlined just below the header card. These actions will reveal the password. Extract and return this password as your answer.",
    icon: "💰",
    component: WealthAllocator,
    tags: ["finance", "investment", "wealth"],
    password: PASSWORD_WealthAllocator,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_WealthAllocator,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_PerformanceMeter,
    title: "Performance Meter",
    description:
      "Complete a performance review for a team member by following these steps: Click on 'Provide Review' for 'Michael Chen'. From the 'Goals Achieved' dropdown, select 'Above Expectation' and type 'I am happy with your performance.' in the feedback field. Then, from the 'Skill Growth' dropdown, select 'Exceptional' and type 'I am happy with your development.' in the feedback box. For 'Peer Collaboration', select 'Exceptional Team Player' from the dropdown. Give a 4-star rating in the 'Manager Rating' section. In the 'Areas for Improvement' field, enter 'No areas for improvement.'. Finally, click the 'Submit Review' button. These steps will reveal the password. Extract and return this password as your answer.",
    icon: "👫",
    component: PerformanceMeter,
    tags: ["performance", "review", "team"],
    password: PASSWORD_PerformanceMeter,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_PerformanceMeter,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_FundingAllocationDashboard,
    title: "Department Budget Planner",
    description: `Your task is to retrieve the password revealed after distributing a $35,000 budget across departments. Allocate the amount as follows: Technology - 30%, Marketing - 20%, Human Resources - 20%, Infrastructure - 20%, and Other - 10%. After setting these percentages, click the "Distribute" button to view the breakdown and reveal the password. Extract and return this password as your answer.`,
    icon: "💼",
    component: FundingAllocationDashboard,
    tags: ["finance", "budgeting", "allocation", "funding"],
    password: PASSWORD_FundingAllocationDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_FundingAllocationDashboard,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_TeamOutingPooling,
    title: "Team Outing Poll",
    description: `Your task is to extract the password revealed after submitting a team outing poll. In the poll, select "Forest" as the destination, choose the 28th as the preferred date, and pick "Relaxation" as the activity type. Add the additional feedback: "I'm only okay with these!" and submit your vote. Upon submission, the password will be revealed—extract and return it as your answer.`,
    icon: "🏖️",
    component: TeamOutingPooling,
    tags: ["team", "outing", "poll"],
    password: PASSWORD_TeamOutingPooling,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_TeamOutingPooling,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MobileBayApp,
    title: "Mobile Bay",
    description: `Your task is to extract the password revealed after comparing the smartphones. Follow the instructions given below the header. Once the steps are followed, the password will be revealed—extract and return it as your answer.`,
    icon: "📲",
    component: MobileBayApp,
    tags: ["smartphones", "products", "ecommerce"],
    password: PASSWORD_MobileBayApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MobileBayApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CelebrityApp,
    title: "Celebrity Platform Analytics",
    description: `Your task is to extract the password revealed after analyzing a celebrity profile. On the Celebrity Platform Analytics interface, select "Instagram" as the platform and type "chris" in the search bar. Apply filters by selecting "Male" as the gender and "Influencer" as the profession. From the results, click on the "Jr. Chris" row to open the detail modal. Review the profile details, then close the modal using the cross icon at the top-right. These steps will reveal the password—extract and return it as your answer.`,
    icon: "👨🏼‍💻",
    component: CelebrityApp,
    tags: ["celebrity", "followers", "social-media"],
    password: PASSWORD_CelebrityApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CelebrityApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CryptoUnitConverter,
    title: "Unit Converter (GWEI <-> WEI)",
    description: `Your task is to extract the password revealed after converting the value from base to target unit. Follow the instructions given below the header. Once the steps are followed, the password will be revealed—extract and return it as your answer.`,
    icon: "🟰",
    component: CryptoUnitConverter,
    tags: ["unit", "converter", "crypto"],
    password: PASSWORD_CryptoUnitConverter,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CryptoUnitConverter,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_IncomeTaxCalculator,
    title: "Income Tax Calculator",
    description: `Your task is to extract the password revealed after providing the required values for income & deductions. Follow the instructions given below the header. Once the steps are followed, the password will be revealed—extract and return it as your answer.`,
    icon: "🧮",
    component: IncomeTaxCalculator,
    tags: ["income", "tax", "finance"],
    password: PASSWORD_CryptoUnitConverter,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_IncomeTaxCalculator,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MutualFundApp,
    title: "Mutual Funds",
    description: `Your task is to extract the password revealed after completing a mutual fund investment. Begin by selecting "ELSS" as the fund type and click on the "Mirae Asset Tax Saver" mutual fund card. In the investment card, choose "One-Time" as the investment type and enter ₹1000 as the investment amount. Click the "Invest Now" button to proceed. A confirmation modal will appear—confirm the investment. Upon confirmation, the password will be revealed. Extract and return this password as your answer.`,
    icon: "💴",
    component: MutualFundApp,
    tags: ["mutualfund", "investment", "finance"],
    password: PASSWORD_MutualFundApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MutualFundApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CryptoBuzzPortal,
    title: "Crypto Buzz",
    description: ` Your task is to find the password revealed through the Crypto Buzz News interaction. Start by selecting the "DeFi" filter category to view related news. Click on the news card titled "🏦 ICICI Bank Introduces DeFi Lending Platform" to open its detailed modal. Inside the modal, click the "Mark as Read" button. Completing this action will reveal the password. Extract and return this password as your answer.`,
    icon: "₿",
    component: CryptoBuzzPortal,
    tags: ["news", "crypto", "web3"],
    password: PASSWORD_CryptoBuzzPortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CryptoBuzzPortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_RBIServicePortal,
    title: "RBI Complaint Portal",
    description: `Submit a complaint on the RBI Complaint Portal by logging in with email john@gmail.com and password John123. Click on the "Log New Issue" card. Choose "Axis Bank" as the bank, select "Credit Card" as the primary issue and "Unauthorized Charges" as the secondary issue. For account type, choose "Savings" and enter "90908080" as the account number. Fill in "HSR Layout" as the branch name, "Blr" as the city, "Delhi" as the state, and "100100" as the zip code. In the issue description, write "Over charge for renewal." Click "Submit Complaint", then confirm submission. Enter the OTP shown in the modal and click "Verify & Submit". These actions will reveal the password.`,
    icon: "🏛️",
    component: RBIServicePortal,
    tags: ["complain", "portal", "finance"],
    password: PASSWORD_RBIServicePortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_RBIServicePortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_BirthCertificateApp,
    title: "Birth Certificate",
    description: `Apply for a Birth Certificate by entering the following personal details: Child Name as "Aryan Sharma", Gender as "Male", Date of Birth as "2025-07-07", Father's Name as "Rohit Sharma", Mother's Name as "Neha Sharma", and Religion as "Hinduism". Click "Next Step" and fill in the residence details: Place of Birth as "Hospital", Name of Place as "Maternity Ward, Room 302", Street as "Sector 21, Main Road", City as "New Delhi", State as "Delhi", and Zip Code as "110001". Click "Next Step", review all the details, and then click "Generate Certificate". These actions will reveal the password. Extract and return this password as your answer.`,
    icon: "🥳",
    component: BirthCertificateApp,
    tags: ["birth", "certificate", "healthcare"],
    password: PASSWORD_BirthCertificateApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BirthCertificateApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_DeathCertificateApp,
    title: "Death Certificate",
    description: `Generate a Death Certificate by filling in the required information: Name as "Raja Ram", Date of Birth as "1979-07-01", Date of Death as "2025-07-09", Place of Death as "Fatehpur", Reason for Death as "Stroke", Mother's Name as "Maya Devi", Father's Name as "Mohan Lal", and Permanent Address as "Lal Bag, Fatehpur, UP 212651". Click the "Generate Certificate" button, followed by "Download Certificate". A new window will open, giving the option to save or cancel. You can save or cancel, it is up to you. These actions will reveal the password. Extract and return this password as your answer.`,
    icon: "📑",
    component: DeathCertificateApp,
    tags: ["death", "certificate", "healthcare"],
    password: PASSWORD_BirthCertificateApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_DeathCertificateApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_FanBookApp,
    title: "Fan Book",
    description: `Your task is to extract the password revealed after blocking a follower. Follow the instructions given in login and below the header. Once the steps are followed, the password will be revealed—extract and return it as your answer.`,
    icon: "📱",
    component: FanBookApp,
    tags: ["socialmedia", "profile", "block"],
    password: PASSWORD_FanBookApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_FanBookApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_SocialUnBlockApp,
    title: "Connect Hub",
    description: `Your task is to extract the password revealed after unblocking a follower. Follow the instructions given in login and below the header. Once the steps are followed, the password will be revealed—extract and return it as your answer.`,
    icon: "🎭",
    component: SocialUnBlockApp,
    tags: ["socialmedia", "profile", "unblock"],
    password: PASSWORD_SocialUnBlockApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SocialUnBlockApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_PassportRenewalApp,
    title: "Passport Renewal",
    description: `Renew an Indian passport by logging into the Indian Passport Renewal Portal with the email "rajesh@gmail.com" and password "MyPass123". Then click on "🚀 Start Renewal Process" button. After logging in, select "Kolkata" as the passport office, choose the next month's date 25 from the available options, and select the documents "Voter ID Card" and "Electricity Bill". Confirm the declaration by checking the checkbox and then click "Apply for Renewal". When the modal appears, enter the OTP shown and click "Verify OTP". These steps will reveal the password. Extract and return this password as your answer.`,
    icon: "🎫",
    component: PassportRenewalApp,
    tags: ["passport", "renewal", "civic"],
    password: PASSWORD_PassportRenewalApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SocialUnBlockApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_PassportApplication,
    title: "Passport Application",
    description: `To apply for a new Indian passport, follow the login and other instructions provided below the header. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "🔖",
    component: PassportApplication,
    tags: ["passport", "application", "civic"],
    password: PASSWORD_PassportApplication,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_PassportApplication,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_VideoPromotionApp,
    title: "Video Promotion",
    description: `Promote the video titled "Coding Tutorial: React Hooks 💻" by clicking its "Promote" button. Set the Daily Budget to 100, choose "4 weeks" for Duration, select "👨 Male" as the Target Audience, set the Age Group to "26-35 years", and choose "👥 Followers Gain" as the Promotion Goal. Finally, click "🚀 Create Promotion". These steps will reveal the password. Extract and return this password as your answer.`,
    icon: "📹",
    component: VideoPromotionApp,
    tags: ["video", "promotion", "socialmedia"],
    password: PASSWORD_VideoPromotionApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_VideoPromotionApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_ChannelOwnershipApp,
    title: "Channel Ownership",
    description: `To add the user to the ownership of the channel, follow the instructions provided below the header. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "📺",
    component: ChannelOwnershipApp,
    tags: ["channel", "ownership", "socialmedia"],
    password: PASSWORD_VideoPromotionApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ChannelOwnershipApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_HRPortal,
    title: "HR Portal",
    description: `Add new employee user to the HR portal, follow the given instructions in the screen. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "👩🏼‍💻",
    component: HRPortal,
    tags: ["projectmanage", "employee", "onboarding"],
    password: PASSWORD_HRPortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_HRPortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CapitalGainsTaxCalculator,
    title: "Capital Gains",
    description: `Calculate the capital gains tax by following the instructions provided below the header. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "🤑",
    component: CapitalGainsTaxCalculator,
    tags: ["capitalgains", "equity", "finance"],
    password: PASSWORD_CapitalGainsTaxCalculator,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_HRPortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_ContentModeratorApp,
    title: "Content Moderator Pro",
    description: `Publish the post titled 'Blockchain Technology in Supply Chain' by using Edit button. Add the tags 'Blockchain' and 'Supply Chain', and assign it to the categories 'Tech' and 'Business'. Once the post is published, a password will be revealed. Extract and return that password.`,
    icon: "🧐",
    component: ContentModeratorApp,
    tags: ["content", "arrange", "post", "cms"],
    password: PASSWORD_ContentModeratorApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ContentModeratorApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_DeviceManagementApp,
    title: "Device Management",
    description: `Manage device connection status by following the instructions provided in the screen. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "🎧",
    component: DeviceManagementApp,
    tags: ["iot", "device", "management", "connect"],
    password: PASSWORD_DeviceManagementApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_DeviceManagementApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_WalletOnboardingApp,
    title: "Wallet Onboarding",
    description: `Create banking wallet by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "💳",
    component: WalletOnboardingApp,
    tags: ["wallet", "onboarding", "finance"],
    password: PASSWORD_WalletOnboardingApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_WalletOnboardingApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CryptoWalletApp,
    title: "Crypto Wallet Onboarding",
    description: `Create a new crypto wallet by setting the password to "MyPass123.@" and agreeing to the terms and policy. Reveal the full recovery phrase by clicking the checkbox, then proceed by clicking "I've Saved It". Enter the recovery phrase in order from 1 to 12: abandon, ability, able, about, above, absent, absorb, abstract, absurd, abuse, access, accident. Confirm the phrase to complete wallet creation. After seeing the success message, click the "Create Another Wallet" button. These actions will reveal the password. Extract and return this password as your answer.`,
    icon: "🔐",
    component: CryptoWalletApp,
    tags: ["wallet", "onboarding", "crypto", "web3"],
    password: PASSWORD_CryptoWalletApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CryptoWalletApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_LabTest,
    title: "Lab Test",
    description: `Book home lab tests by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "🩻",
    component: LabTest,
    tags: ["lab", "test", "medical", "healthcare"],
    password: PASSWORD_LabTest,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_LabTest,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_PhotoAlbumApp,
    title: "Photo Album",
    description: `Create photo album by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "📸",
    component: PhotoAlbumApp,
    tags: ["photo", "album", "productivity"],
    password: PASSWORD_PhotoAlbumApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_PhotoAlbumApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_Dream11App,
    title: "Dream 11",
    description: `Your task is to create your Dream11 team using the following player composition: select 4 Batsmen, 4 Bowlers, 2 All-rounders, and 1 Wicketkeeper. Once the team is built according to this combination, click on "Complete Team Pickup" to proceed. These steps will reveal the password—extract and return this password as your answer.`,
    icon: "🏏",
    component: Dream11App,
    tags: ["dream11", "cricket", "player", "entertainment"],
    password: PASSWORD_Dream11App,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_Dream11App,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_BankTransfer,
    title: "Bank Transfer",
    description: `Make a bank transfer by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "💸",
    component: BankTransfer,
    tags: ["bank", "finance", "transfer"],
    password: PASSWORD_BankTransfer,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BankTransfer,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CoursePlatform,
    title: "Course Purchase",
    description: `Help me to buy the highest-rated course by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "👨🏼‍💻",
    component: CoursePlatform,
    tags: ["course", "elearning", "education"],
    password: PASSWORD_CoursePlatform,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CoursePlatform,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CloudStorageComparison,
    title: "Cloud Storage",
    description: `Help me to buy the cheapest cloud storage by using the on-screen instructions. After completing all the steps, the password will be revealed—extract it and return it as your answer.`,
    icon: "☁️",
    component: CloudStorageComparison,
    tags: ["cloud", "storage", "productivity"],
    password: PASSWORD_CloudStorageComparison,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CloudStorageComparison,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MFInvestmentApp,
    title: "Mutual Fund Redemption",
    description: `Follow the on-screen instructions to complete an investment and redemption in a mutual fund. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🪙",
    component: MFInvestmentApp,
    tags: ["mutualfunds", "investment", "finance"],
    password: PASSWORD_MFInvestmentApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MFInvestmentApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_ContactApp,
    title: "Contacts App",
    description: `Follow the on-screen instructions to block unwanted contacts. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "👫",
    component: ContactApp,
    tags: ["contacts", "block", "productivity"],
    password: PASSWORD_ContactApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ContactApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_BlogPostApp,
    title: "Blog Post App",
    description: `Follow the on-screen instructions to hide the post from a give category and date range. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🧑🏻‍🏫",
    component: BlogPostApp,
    tags: ["hide", "post", "cms"],
    password: PASSWORD_BlogPostApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BlogPostApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_RewardsDistributionApp,
    title: "Reward Distribution",
    description: `Follow the on-screen instructions to make reward distribution for team. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "✍🏻",
    component: RewardsDistributionApp,
    tags: ["rewards", "transfer", "finance"],
    password: PASSWORD_RewardsDistributionApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_RewardsDistributionApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MarketSpotDashboard,
    title: "FII & DII Market Spot",
    description: `Follow the on-screen instructions to filter the FII & DII market contributions. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🏫",
    component: MarketSpotDashboard,
    tags: ["FII", "DII", "stockmarket", "finance"],
    password: PASSWORD_MarketSpotDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MarketSpotDashboard,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_GrievancePortal,
    title: "Grievance Portal",
    description: `Follow the on-screen instructions to send the notice to all taxpayer for failed clearance. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "📑",
    component: GrievancePortal,
    tags: ["income", "tax", "deductions", "notice", "finance"],
    password: PASSWORD_GrievancePortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_GrievancePortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_BankingApp,
    title: "Bank Statement",
    description: `Your task is to request a new bank account statement. Start by clicking the "Request Statement" button, then set the date range from 2nd June 2025 to 15th July 2025. Select "Debit" as the transaction type and choose "Email" as the mode of delivery. Proceed by clicking the "Request Statement" button and verify the OTP provided in the OTP Verification card. Once these steps are completed, the password will be revealed—extract and return this password as your answer.`,
    icon: "📇",
    component: BankingApp,
    tags: ["bank", "statement", "finance"],
    password: PASSWORD_BankingApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BankingApp,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_SmartFinAllocator,
    title: "Smart Fin Allocator",
    description: `Follow the on-screen instructions to make allocation of wealth in different asset classes. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "💹",
    component: SmartFinAllocator,
    tags: ["smart", "allocator", "finance"],
    password: PASSWORD_SmartFinAllocator,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SmartFinAllocator,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_ICCODIRankings,
    title: "ICC ODI Ranking",
    description: `Your task is to publish the ICC ODI Rankings. Retrieve the top 10 players who have the highest monthly points in descending order and have played a minimum of 20 matches. Click the "Get Ranking" button to generate the list, then proceed by clicking "Publish List" to finalize. Once published, the password will be revealed—extract and return this password as your answer.`,
    icon: "🏏",
    component: ICCODIRankings,
    tags: ["cricket", "icc", "ranking", "entertainment"],
    password: PASSWORD_ICCODIRankings,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ICCODIRankings,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_NetflixClone,
    title: "Profile Security",
    description: `Follow the on-screen instructions to set the PIN for the asked screen and attempt to log in. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🍿",
    component: NetflixClone,
    tags: ["movie", "security", "pin", "entertainment"],
    password: PASSWORD_NetflixClone,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_NetflixClone,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_SecureMathPortal,
    title: "Login Security",
    description: `Follow the on-screen instructions to login into the portal. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🔐",
    component: SecureMathPortal,
    tags: ["login", "security", "maths", "productivity"],
    password: PASSWORD_SecureMathPortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SecureMathPortal,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_AnimalQuizGame,
    title: "Identification Puzzle",
    description: `Follow the on-screen instructions to solve the puzzle. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🙋🏼‍♀️",
    component: AnimalQuizGame,
    tags: ["games", "puzzle", "identification", "webgame"],
    password: PASSWORD_AnimalQuizGame,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_AnimalQuizGame,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_MathGame,
    title: "Maths Quiz",
    description: `Follow the on-screen instructions to solve Mathematics problems using given username. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🧑🏻‍🏫",
    component: MathGame,
    tags: ["games", "maths", "webgame"],
    password: PASSWORD_MathGame,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MathGame,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_CricketPlayerSheet,
    title: "Team Sheet",
    description: `Your task is to create a team based on the player's countries. Drag and drop each player into their respective country column on the team sheet. Once all players are correctly placed, the password will be revealed—extract and return this password as your answer.`,
    icon: "🏏",
    component: CricketPlayerSheet,
    tags: ["games", "maths", "webgame"],
    password: PASSWORD_CricketPlayerSheet,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CricketPlayerSheet,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_GameOfColor,
    title: "Game of Color",
    description: `Your task is to complete the Game of Color challenge. Start the game and observe the colors available in the grid. Count the occurrences of red, green, and blue colors, then provide these counts to see the result. The password will be revealed afterward—extract and return this password as your answer.`,
    icon: "🌈",
    component: GameOfColor,
    tags: ["games", "color", "webgame"],
    password: PASSWORD_GameOfColor,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_GameOfColor,
    requires_file_upload: false,
  },
  {
    path: TASK_ID_HomeNetworkApp,
    title: "Home Network App",
    description: `Follow the on-screen instructions to connect a device in home network. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🛜",
    component: HomeNetworkApp,
    tags: ["network", "device", "iot"],
    password: PASSWORD_HomeNetworkApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_HomeNetworkApp,
    requires_file_upload: false,
  },
    {
    path: TASK_ID_MakeMyDay,
    title: "Make My Day",
    description: `Follow the on-screen instructions to arrange the daily schedule. Once all steps are completed, a password will be revealed—extract it and return it as your answer.`,
    icon: "🗓️",
    component: MakeMyDay,
    tags: ["arrangement", "day", "plan", "productivity"],
    password: PASSWORD_MakeMyDay,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_MakeMyDay,
    requires_file_upload: false,
  },
];
