import AnimeBrowser, {
  PASSWORD_AnimeBrowser,
  TASK_ID_AnimeBrowser,
} from "../pages/AnimeBrowser";
import Assignsubtask, {
  PASSWORD_Assignsubtask,
  TASK_ID_Assignsubtask,
} from "../pages/Assignsubtask";
import CollegeFinder, {
  PASSWORD_CollegeFinder,
  TASK_ID_CollegeFinder,
} from "../pages/CollegeFinder";
import CommunityPollApp, {
  PASSWORD_CommunityPollApp,
  TASK_ID_CommunityPollApp,
} from "../pages/CommunityPollApp";
import CreditCardBillSimulator, {
  PASSWORD_CreditCardBillSimulator,
  TASK_ID_CreditCardBillSimulator,
} from "../pages/CreditCardBillSimulator";
import DynamicSurvey, {
  PASSWORD_DynamicSurvey,
  TASK_ID_DynamicSurvey,
} from "../pages/DynamicSurvey";
import FinanceDashboard, {
  PASSWORD_FinanceDashboard,
  TASK_ID_FinanceDashboard,
} from "../pages/FinanceDashboard";
import IsuueReporter, {
  PASSWORD_IsuueReporter,
  TASK_ID_IsuueReporter,
} from "../pages/IsuueReporter";
import LightControlDashboard, {
  PASSWORD_LightControlDashboard,
  TASK_ID_LightControlDashboard,
} from "../pages/LightControlDashboard";
import CreateEMI, {
  PASSWORD_RecurringEMI,
  TASK_ID_RecurringEMI,
} from "../pages/CreateEMI";
import ReviewContract, {
  PASSWORD_ReviewContract,
  TASK_ID_ReviewContract,
} from "../pages/ReviewContract";
import SetTemperature, {
  PASSWORD_SetTemperature,
  TASK_ID_SetTemperature,
} from "../pages/SetTemperature";
import SetupRecurringSIP, {
  PASSWORD_SetupRecurringSIP,
  TASK_ID_SetupRecurringSIP,
} from "../pages/SetupRecurringSIP";
import { RouteConfig } from "./routeType";
import SmartHomeUI, {
  PASSWORD_SmartHomeUI,
  TASK_ID_SmartHomeUI,
} from "../pages/SmartHomeUI";
import SleepTrackerDashboard, {
  PASSWORD_SleepTrackerDashboard,
  TASK_ID_SleepTrackerDashboard,
} from "../pages/SleepTrackerDashboard";
import WidgetDashboard, {
  PASSWORD_WidgetDashboard,
  TASK_ID_WidgetDashboard,
} from "../pages/WidgetDashboard";
import ChronologicalOrder, {
  PASSWORD_ChronologicalOrder,
  TASK_ID_ChronologicalOrder,
} from "../pages/ChronologicalOrder";
import BotProfileDetection, {
  PASSWORD_BotProfileDetection,
  TASK_ID_BotProfileDetection,
} from "../pages/BotProfileDetection";
import CmsDashboard, {
  PASSWORD_CmsDashboard,
  TASK_ID_CmsDashboard,
} from "../pages/CmsDashboard";
import SocialFeed, {
  PASSWORD_SocialFeed,
  TASK_ID_SocialFeed,
} from "../pages/SocialFeed";
import {
  PASSWORD_TripSettlement,
  TASK_ID_TripSettlement,
  TripSettlement,
} from "../pages/TripSettlement";
import SocialMediaDashboard, {
  PASSWORD_SocialMediaDashboard,
  TASK_ID_SocialMediaDashboard,
} from "../pages/SocialMediaDashboard";
import BudgetingPortal, {
  PASSWORD_BudgetingPortal,
  TASK_ID_BudgetingPortal,
} from "../pages/BudgetingPortal";
import InvestmentDashboard, {
  PASSWORD_InvestmentDashboard,
  TASK_ID_InvestmentDashboard,
} from "../pages/InvestmentDashboard";
import EnergyUsage, {
  PASSWORD_EnergyUsage,
  TASK_ID_EnergyUsage,
} from "../pages/EnergyUsage";
import EmergencyConsult, {
  PASSWORD_EmergencyConsult,
  TASK_ID_EmergencyConsult,
} from "../pages/EmergencyConsult";
import RandomCoupon, {
  PASSWORD_RandomCoupon,
  TASK_ID_RandomCoupon,
} from "../pages/RandomCoupon";
import PollApp, { PASSWORD_PollApp, TASK_ID_PollApp } from "../pages/PollApp";
import TokenSwapApp, {
  PASSWORD_TokenSwapApp,
  TASK_ID_TokenSwapApp,
} from "../pages/TokenSwapApp";
import Airdrop, {
  PASSWORD_AirdropWebsite,
  TASK_ID_AirdropWebsite,
} from "../pages/Airdrop";
import NFTCollection, {
  PASSWORD_NFTCollection,
  TASK_ID_NFTCollection,
} from "../pages/NFTCollection";
import StoryPostingApp, {
  PASSWORD_StoryPostingApp,
  TASK_ID_StoryPostingApp,
} from "../pages/StoryPostingApp";
import AQIMonitor, {
  PASSWORD_AQIMonitor,
  TASK_ID_AQIMonitor,
} from "../pages/AQIMonitor";
import OrderHistoryDashboard, { PASSWORD_OrderHistoryDashboard, TASK_ID_OrderHistoryDashboard } from "../pages/OrderHistoryDashboard";
import TransactionTemplates, { PASSWORD_TransactionTemplates, TASK_ID_TransactionTemplates } from "../pages/TransactionTemplates";
import SmartMeterDashboard, { PASSWORD_SmartMeterDashboard, TASK_ID_SmartMeterDashboard } from "../pages/SmartMeterDashboard";
import StreamingDashboard, { PASSWORD_StreamingDashboard, TASK_ID_StreamingDashboard } from "../pages/StreamingDashboard";
import FollowerAnalytics, { PASSWORD_FollowerAnalytics, TASK_ID_FollowerAnalytics } from "../pages/FollowerAnalytics";
import NumberSequencePuzzle, { PASSWORD_NumberSequencePuzzle, TASK_ID_NumberSequencePuzzle } from "../pages/NumberSequencePuzzle";
import Sudoku, { PASSWORD_Sudoku, TASK_ID_Sudoku } from "../pages/Sudoku";
import SettingsInterface, { PASSWORD_SettingsInterface, TASK_ID_SettingsInterface } from "../pages/SettingsInterface";
import CSSVisualEditor, { PASSWORD_CCSSVisualEditor, TASK_ID_CCSSVisualEditor } from "../pages/CSSVisualEditor";
import AnimationDebugInterface, { PASSWORD_ButtonAnimation, TASK_ID_ButtonAnimation } from "../pages/AnimationDebugInterface";
import CountryCapital, { PASSWORD_CountryCapital, TASK_ID_CountryCapital } from "../pages/CountryCapital";
import PatternRecognition, { PASSWORD_PatternRecognition, TASK_ID_PatternRecognition } from "../pages/PatternRecognition";
import StudentProgressChart, { PASSWORD_StudentProgressChart, TASK_ID_StudentProgressChart } from "../pages/StudentProgressChart";

export const routes_5: RouteConfig[] = [
  {
    path: TASK_ID_CollegeFinder,
    title: "College Finder",
    description: `Your goal is to find a college that meets specific criteria on the website. Start by clicking on the Location field and entering 'New York'. Next, click on the Course field and enter 'Medicine'. After that, select the College Type as 'Private'. Set the maximum ranking to 15 and the maximum fees to 60,000. Once all the filters are applied, click the "Select College" button for 'Stanford University' that appears in the results. When the task is successfully completed, a password will be displayed on the screen. Return this password as your final answer.`,
    icon: "🎓",
    component: CollegeFinder,
    tags: ["college", "search", "online"],
    password: PASSWORD_CollegeFinder,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CollegeFinder,
  },
  {
    path: TASK_ID_AnimeBrowser,
    title: "Anime Browser",
    description: `Your task is to find and add two specific anime to the watch-later list. Scroll through the page and locate the anime titled "Attack on Titan", then click the "Add to Watch Later" button. Repeat the same process for the anime "Deathnote". Once both are successfully added, a password will appear on the screen. Return this password as your final answer.`,
    icon: "🎬",
    component: AnimeBrowser,
    tags: ["anime", "search", "online"],
    password: PASSWORD_AnimeBrowser,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_AnimeBrowser,
  },
  {
    path: TASK_ID_CreditCardBillSimulator,
    title: "Credit-Card Bill Simulator",
    description: `Your goal is to simulate a credit card bill payment. Begin by entering the card number "4532 1234 5678 9012" in the Card Number field. Then, fill in the Expiry Date as March of next year in the format "MM/YY", and enter "123" as the CVV. Provide "Jhon Doe" as the Cardholder Name. After filling in the details, click the "Get Bill Details" button to retrieve the due amount and due date. Once the bill information is displayed, proceed by clicking the "Pay Now" button to complete the payment. Upon successful payment, a password will appear on the screen—return this password as your final answer.`,
    icon: "💰",
    component: CreditCardBillSimulator,
    tags: ["finance", "forms", "bill", "payment"],
    password: PASSWORD_CreditCardBillSimulator,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CreditCardBillSimulator,
  },
  {
    path: TASK_ID_DynamicSurvey,
    title: "Dynamic Survey",
    description: `Your task is to complete a 3-step interactive survey. Fill in your name as "Jhon Doe", occupation as "Software Developer", and choose age as "18-25" and location as "Asia" from dropdowns and click on "Next" button. Select Favorite Color as "Red", Music Genre as "Pop", Travel Frequency as "Never", Exercise Habits as "Daily" and click on "Next" button. Select Overall Satisfaction as "Very Satisfied", Recommendations as "Definitely", add Areas for Improvement as "No" and add Additional Comments "No" and click on "Complete Survey" button. After submission, a screen will show the password “survey-done”. Return this password as your final answer.`,
    icon: "📝",
    component: DynamicSurvey,
    tags: ["survey", "forms"],
    password: PASSWORD_DynamicSurvey,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_DynamicSurvey,
  },
  {
    path: TASK_ID_CommunityPollApp,
    title: "Community Poll App",
    description: `Your goal is to take part in a local community poll. Browse through the options, each shown with images and descriptions, and select the 'Sports Complex' as your choice and click the 'Cast My Vote 🗳️' button. After submitting your vote, a confirmation screen will display the secret password. Return this password as your final answer.`,
    icon: "📊",
    component: CommunityPollApp,
    tags: ["Civic", "Voting"],
    password: PASSWORD_CommunityPollApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CommunityPollApp,
  },
  {
    path: TASK_ID_Assignsubtask,
    title: "Assign Sub Task",
    description: `Your goal is to create a new task and link a sub-task to it. Start by entering task title as "Meeting", add a description "meeting", select the category as "Work" and click the "Create Task" button. Once the task is created, add a sub-task named "Take Note" and set "Meeting" as its parent task and click on "Link Sub-task" button. After successfully linking the sub-task, a screen will display a secret password. Return this password as your final answer.`,
    icon: "🎯",
    component: Assignsubtask,
    tags: ["Project", "Task"],
    password: PASSWORD_Assignsubtask,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_Assignsubtask,
  },
  {
    path: TASK_ID_ReviewContract,
    title: "Review Contract",
    description: `Your goal is to review a contract document displayed on the screen. Scroll all the way to the bottom, then type "Jhon Doe" in the signature field provided. After that click on "Sign Contract" button. Once you’ve signed the contract, a  secret password will appear on the screen. Return this password as your final answer.`,
    icon: "🧾",
    component: ReviewContract,
    tags: ["Contract", "E-Signature"],
    password: PASSWORD_ReviewContract,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ReviewContract,
  },
  {
    path: TASK_ID_LightControlDashboard,
    title: "Light Control Dashboard",
    description: `Your task is to retrieve the password shown after controlling the smart home interface. Begin by turning off the lights in the Kitchen, Living Room, and Bathroom. Then, lock the Front Door. Once all actions are completed, a confirmation screen will appear displaying a password—extract and return this password as your final answer.`,
    icon: "⚙️",
    component: LightControlDashboard,
    tags: ["Iot", "Automation"],
    password: PASSWORD_LightControlDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_LightControlDashboard,
  },
  {
    path: TASK_ID_SetTemperature,
    title: "Set Temperature",
    description: `Set up a smart-home rule named "Turn on AC" that triggers when "Living Room Temperature" is greater than "30°C". The action should set "Living Room AC" to "22°C". After creating the rule, locate it in the Smart Home Rules section and trigger it to reveal a secret password. Return this password as your final answer.`,
    icon: "⚙️",
    component: SetTemperature,
    tags: ["Iot", "Automation"],
    password: PASSWORD_SetTemperature,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SetTemperature,
  },
  {
    path: TASK_ID_SetupRecurringSIP,
    title: "Setup Recurring SIP",
    description: `Set up a recurring SIP of "5000" in the mutual fund “Growth Index 2030” with a debit date on the "15th of every month". After starting the, retrieve the secret password shown on the confirmation screen and return it as your final answer.`,
    icon: "💰",
    component: SetupRecurringSIP,
    tags: ["finiance", "SIP"],
    password: PASSWORD_SetupRecurringSIP,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SetupRecurringSIP,
  },
  {
    path: TASK_ID_IsuueReporter,
    title: "Issue Reporter",
    description: `Search for public issues in the "City Center" area with ZIP code "12345". Locate the pending issue titled "Potholes Need Repair", vote on it, and post a comment with the title 'Potholes Need Repair', and the ZIP code "12345". Once completed, a secret password will appear—return it as your final answer.`,
    icon: "⚠️",
    component: IsuueReporter,
    tags: ["Civic", "Report Issue"],
    password: PASSWORD_IsuueReporter,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_IsuueReporter,
  },
  {
    path: TASK_ID_RecurringEMI,
    title: "Create EMI",
    description: `Add a recurring SIP of "2315" date on the "5th of every month" with tag "Debt" and reminder "3 days before". Retrieve the secret password shown on the confirmation screen and return it as your final answer.`,
    icon: "💼",
    component: CreateEMI,
    tags: ["Finiance", "EMI"],
    password: PASSWORD_RecurringEMI,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_RecurringEMI,
  },
  {
    path: TASK_ID_FinanceDashboard,
    title: "Finance Dashboard",
    description: `Your goal is to generate a graph showing weekly food expenses and identify the week with highest spend. Scroll to the Set Expense Trends section, select the "Food" category, and click the "Highest Weekly" button. Return the secret password shown on the confirmation screen.`,
    icon: "💰",
    component: FinanceDashboard,
    tags: ["Finiance", "Expenses"],
    password: PASSWORD_FinanceDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_FinanceDashboard,
  },
  // 15 JULY
  {
    path: TASK_ID_AQIMonitor,
    title: "AQI Monitor",
    description: `Review the Air Quality Index by entering "Mumbai" and retrieving the data. In the Critical AQI Alert System section, search and select the area with the highest AQI and submit the critical report. Return the secret password shown on the confirmation screen.`,
    icon: "🏛️",
    component: AQIMonitor,
    tags: ["Civic", "AQI"],
    password: PASSWORD_AQIMonitor,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_AQIMonitor,
  },
  {
    path: TASK_ID_StoryPostingApp,
    title: "Story Posting App",
    description: `Create a new story, add the caption “Dev Life 💻☕”, and tag "@techtwins". Post the story, then return the secret password shown on the confirmation screen.`,
    icon: "✍️",
    component: StoryPostingApp,
    tags: ["Social Media", "Story"],
    password: PASSWORD_StoryPostingApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_StoryPostingApp,
  },
  {
    path: TASK_ID_NFTCollection,
    title: "NFT Collection",
    description: `View your NFT collection and filter by artist "SarahXYZ". Locate the NFT titled "Pixel Genesis #5", click "Send NFT", enter "0x987abcd" as the recipient wallet address and "30000" as the gas limit. Transfer the NFT and return the secret password shown on the confirmation screen.`,
    icon: "🔄",
    component: NFTCollection,
    tags: ["swap", "wallet", "NFT"],
    password: PASSWORD_NFTCollection,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_NFTCollection,
  },
  {
    path: TASK_ID_AirdropWebsite,
    title: "Airdrop Reward",
    description: `Claim your airdrop reward and transfer the entire balance to the wallet address "0x987abcd". Return the secret password shown on the confirmation screen.`,
    icon: "💰",
    component: Airdrop,
    tags: ["Transfer", "wallet", "NFT"],
    password: PASSWORD_AirdropWebsite,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_AirdropWebsite,
  },
  {
    path: TASK_ID_TokenSwapApp,
    title: "Token Swap App",
    description: `Swap 20 TESTCOIN to FUELTOKEN with a slippage tolerance of 1%. After completing the swap, go to the history section and delete the transaction for the swap you just made. Return the secret password shown on the confirmation screen.`,
    icon: "🔄",
    component: TokenSwapApp,
    tags: ["Swap", "Token"],
    password: PASSWORD_TokenSwapApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_TokenSwapApp,
  },
  {
    path: TASK_ID_PollApp,
    title: "Poll App",
    description: `Navigate to Create POll section. Create a poll with the question “Best IDE for Python?” and options "VS Code", "PyCharm", and "Jupyter". Set the duration to 3 days and submit the poll. Return the secret password shown on the confirmation screen.`,
    icon: "📊",
    component: PollApp,
    tags: ["Poll", "Social Media"],
    password: PASSWORD_PollApp,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_PollApp,
  },
  {
    path: TASK_ID_RandomCoupon,
    title: "Random Coupon",
    description: `Add any item to your cart from the store. Apply the first coupon code which have highest discount. Once the discount is correctly applied, proceed to checkout using the Pay with UPI option. If all steps are done correctly, a secret password will appear on the screen. Return that secret password.`,
    icon: "🛍️",
    component: RandomCoupon,
    tags: ["Coupon", "Shopping"],
    password: PASSWORD_RandomCoupon,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_RandomCoupon,
  },
  {
    path: TASK_ID_EmergencyConsult,
    title: "Emergency Consult",
    description: `Log health symptoms for 3 consecutive days. Day 1: "chest pain" with severity 2 and notes "chest pain". Day 2: "nausea" with severity 2 and notes "nausea". Day 3: repeat the same as Day 1. Return the secret password shown on the confirmation screen.`,
    icon: "🏨",
    component: EmergencyConsult,
    tags: ["Health", "Consult"],
    password: PASSWORD_EmergencyConsult,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_EmergencyConsult,
  },
  {
    path: TASK_ID_EnergyUsage,
    title: "Energy Usage",
    description: `Navigate to the kitchen, and check the appliances listed. Identify which appliance used higghest energy, and click on it. If you select the correct appliance, a secret password will appear on the screen. Return that password.`,
    icon: "⚙️",
    component: EnergyUsage,
    tags: ["Energy", "Automation"],
    password: PASSWORD_EnergyUsage,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_EnergyUsage,
  },
  {
    path: TASK_ID_InvestmentDashboard,
    title: "Investment Dashboard",
    description: `Explore all the available investment options on the dashboard. Review their 1-year return rates. Identify the investment with the lowest return in 1 year, and then withdraw the full amount from that specific investment. Once you've completed the withdrawal, a secret password will be shown on the screen. Return that password.`,
    icon: "💰",
    component: InvestmentDashboard,
    tags: ["Investment", "Funds"],
    password: PASSWORD_InvestmentDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_InvestmentDashboard,
  },
  // 16 JULY
  {
    path: TASK_ID_BudgetingPortal,
    title: "Budgeting Portal",
    description: `On the Participatory Budgeting Portal, you have ₹100 crores to allocate across five public categories: Education, Roads, Health, Environment, and Housing. Use the sliders or drag controls to distribute the full amount. Make sure that no category receives less than ₹10 crores, and Health receives the highest allocation. Once you’ve allocated the funds correctly, a logic confirmation pop-up will appear, a secret password will be revealed. Return that password.`,
    icon: "💰",
    component: BudgetingPortal,
    tags: ["Budget", "Transfer"],
    password: PASSWORD_BudgetingPortal,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BudgetingPortal,
  },
  {
    path: TASK_ID_SocialMediaDashboard,
    title: "Social-Media Dashboard",
    description: `Scroll the Social Media Dashboard. Review your posts and analyze their engagement metrics—likes, comments, shares, and follower count. Identify the post with the highest engagement-to-follower ratio. Once you’ve found it, click “Save as Best Practice Example.” Secret password will appear on the screen. Return that password.`,
    icon: "🚀",
    component: SocialMediaDashboard,
    tags: ["Social-Media", "Dashboard"],
    password: PASSWORD_SocialMediaDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SocialMediaDashboard,
  },
  {
    path: TASK_ID_TripSettlement,
    title: "Trip Settlement",
    description: `Your goal is to settle expenses from a recent group trip. Review the balances among your four friends and identify the person you owe the most money. Initiate a UPI payment to that person. After completing the payment. Find the person who should receive the most money and mark as Paid. Once the person is paid and the status is updated, a secret password will be displayed. Return this password as your final answer.`,
    icon: "💰",
    component: TripSettlement,
    tags: ["Finiance", "Settlement"],
    password: PASSWORD_TripSettlement,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_TripSettlement,
  },
  {
    path: TASK_ID_SocialFeed,
    title: "Social Feed",
    description: `Scroll through the replies on the trending post. Look closely at each response and identify the one that appears to be auto-generated or bot-like based on its tone or wording. Open the three-dot menu on that reply and select “Mark as Likely Bot". Once you select the reply, a secret password will be shown on the screen. Return that password.`,
    icon: "🚀",
    component: SocialFeed,
    tags: ["Social Media", "Feed"],
    password: PASSWORD_SocialFeed,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SocialFeed,
  },
  {
    path: TASK_ID_CmsDashboard,
    title: "CMS Dashboard",
    description: `Your goal is to manage landing page versions in your CMS dashboard. Preview Version A and Version B carefully. Identify which version has a broken image and no CTA button. Disable that version using the toggle switch, and from the dropdown, set the other version as “Live.” Once the correct version is disabled and the correct one is made live, a secret password will be displayed. Return this password as your final answer.`,
    icon: "⚙️",
    component: CmsDashboard,
    tags: ["CMS", "Comparision"],
    password: PASSWORD_CmsDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CmsDashboard,
  },
  {
    path: TASK_ID_BotProfileDetection,
    title: "Bot Profile Detection",
    description: `Your goal is to identify suspicious user profiles. Look through the list and find all profiles that have zero posts or the same profile picture. Select those profiles using the checkboxes provided. Once all correct profiles are flagged, a secret password will be displayed. Return this password as your final answer.`,
    icon: "💬",
    component: BotProfileDetection,
    tags: ["Profile", "Social Media"],
    password: PASSWORD_BotProfileDetection,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_BotProfileDetection,
  },
  // 17 JULY
  {
    path: TASK_ID_ChronologicalOrder,
    title: "Chronological Order",
    description: `Reorder the 8 shown movies based on their release date in an ascending order. When the correct order is achieved, you’ll unlock the secret password. Return this password as answer.`,
    icon: "🎬",
    component: ChronologicalOrder,
    tags: ["movie", "analysis", "entrainment"],
    password: PASSWORD_ChronologicalOrder,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ChronologicalOrder,
  },
  {
    path: TASK_ID_WidgetDashboard,
    title: "Widget Dashboard",
    description: `A content dashboard loads 4 widgets. One of them fails to load. Your task is to detect the faulty widget and disable it using the inline toggle. If you disable the correct one, a secret password will be revealed. Return this password as answer.`,
    icon: "⚙️",
    component: WidgetDashboard,
    tags: ["CMS", "Widget"],
    password: PASSWORD_WidgetDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_WidgetDashboard,
  },
  {
    path: TASK_ID_SleepTrackerDashboard,
    title: "Sleep Tracker Dashboard",
    description: `Your goal is to review 7 sleep sessions from the past week. Identify all sessions where the sleep duration is less than 4 hours. For those sessions, use the dropdown to mark it as "Insufficient Sleep". Once all sessions are correctly flagged, a secret password will be revealed on screen. Return this as your answer.`,
    icon: "🏨",
    component: SleepTrackerDashboard,
    tags: ["Health", "Sleep"],
    password: PASSWORD_SleepTrackerDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SleepTrackerDashboard,
  },
  {
    path: TASK_ID_SmartHomeUI,
    title: "Smart Home UI",
    description: `On the Smart Home Dashboard, check the weather forecast for tomorrow— it could be sunny, rainy, or windy. Based on the forecast shown: If it’s sunny, schedule the sprinkler to run at 6 AM. If it’s rainy, skip the watering schedule. If it’s windy, set it to run for 30 minutes only. Once you’ve selected the correct option secret password will appear. Return that password.`,
    icon: "⚙️",
    component: SmartHomeUI,
    tags: ["Iot", "Smart Home"],
    password: PASSWORD_SmartHomeUI,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SmartHomeUI,
  },
    // 18 JULY
  {
    path: TASK_ID_OrderHistoryDashboard,
    title: "Order History Dashboard",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "🛍️",
    component: OrderHistoryDashboard,
    tags: ["E-commerce","Order History"],
    password: PASSWORD_OrderHistoryDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_OrderHistoryDashboard,
  },
  {
    path: TASK_ID_TransactionTemplates,
    title: "Transaction Templates",
    description: `Your goal is to review 5 bank transactions and label each with the correct category using the dropdown menu. Once all transactions are correctly categorized based on their descriptions, a secret password will be revealed on the screen. Return this as answer`,
    icon: "💰",
    component: TransactionTemplates,
    tags: ["Finiance","Transaction"],
    password: PASSWORD_TransactionTemplates,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_TransactionTemplates,
  },
  {
    path: TASK_ID_SmartMeterDashboard,
    title: "Smart Meter Dashboard",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "⚙️",
    component: SmartMeterDashboard,
    tags: ["Finiance","Transaction"],
    password: PASSWORD_SmartMeterDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SmartMeterDashboard,
  },
  {
    path: TASK_ID_StreamingDashboard,
    title: "Streaming Dashboard",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "🎬",
    component: StreamingDashboard,
    tags: ["Movie","entrainment"],
    password: PASSWORD_StreamingDashboard,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_StreamingDashboard,
  },
  {
    path: TASK_ID_FollowerAnalytics,
    title: "Follower Analytics",
    description: `Open the Follower Analytics Dashboard for the specified account. Sort the follower list by Join Date and Engagement Ratio. Identify users who have an engagement ratio less than 0.1 and whose accounts are less than 2 weeks old. For each of these users, open the Action dropdown, select “Flag as Likely Bot”, and then choose “Block.”Once all correct users have been flagged and blocked, a secret password will appear. Return that password.`,
    icon: "🎯",
    component: FollowerAnalytics,
    tags: ["Profile", "Social Media"],
    password: PASSWORD_FollowerAnalytics,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_FollowerAnalytics,
  },
  // 21 JULY
  {
    path: TASK_ID_NumberSequencePuzzle,
    title: "Number Sequence Puzzle",
    description: `View the Number Sequence Puzzle on the screen. One number in the 5-number sequence is missing. Analyze the pattern and use the dropdown to select the correct missing number. Choose the correct answer, a secret password will appear. Return that password.`,
    icon: "🎯",
    component: NumberSequencePuzzle,
    tags: ["Number Sequence", "Puzzle"],
    password: PASSWORD_NumberSequencePuzzle,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_NumberSequencePuzzle,
  },
  {
    path: TASK_ID_Sudoku,
    title: "Sudoku",
    description: `Complete the 4x4 Sudoku board by dragging number tiles from the side panel into the empty cells. Follow standard Sudoku rules—no repeating numbers in any row, column, or 2x2 box. If you drop a number in an invalid spot, the cell will highlight red. Once the board is correctly filled with all valid numbers, submit your solution. A secret password will appear if your answer is correct. Return that password.`,
    icon: "🎮",
    component: Sudoku,
    tags: ["Sudoku"],
    password: PASSWORD_Sudoku,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_Sudoku,
  },
  {
    path: TASK_ID_SettingsInterface,
    title: "Settings Interface",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "⚙️",
    component: SettingsInterface,
    tags: ["Navigation"],
    password: PASSWORD_SettingsInterface,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_SettingsInterface,
  },
  {
    path: TASK_ID_CCSSVisualEditor,
    title: "CSS Visual Editor",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "⚙️",
    component: CSSVisualEditor,
    tags: ["Logic Game", "Puzzle"],
    password: PASSWORD_CCSSVisualEditor,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CCSSVisualEditor,
  },
  {
    path: TASK_ID_ButtonAnimation,
    title: "Animation Debug Interface",
    description: `Several buttons animate onto the screen. One of them has the wrong animation speed—it might appear too quickly or too slowly compared to the others. Use the replay button to observe all animations carefully.Identify the button with incorrect timing, then adjust its animation duration to match the others. When the timing is corrected, a secret password will appear. Return that password.`,
    icon: "🎮",
    component: AnimationDebugInterface,
    tags: ["puzzle", "Animation"],
    password: PASSWORD_ButtonAnimation,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_ButtonAnimation,
  },
  {
    path: TASK_ID_CountryCapital,
    title: "Country Capital",
    description: `Match each country listed below to its correct capital city using the dropdown menus. All countries and capital options are randomized for this session.Once you've made a selection for each country, and if all your matches are correct, a secret password will appear. Return that password.`,
    icon: "👤",
    component: CountryCapital,
    tags: ["E-learning","Geography"],
    password: PASSWORD_CountryCapital,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_CountryCapital,
  },
  {
    path: TASK_ID_PatternRecognition,
    title: "Pattern Recognition",
    description: `One symbol is missing in the 3x3 grid. Use the pattern across rows and columns to deduce the correct symbol. Select your answer. For correct answer, the secret password will be revealed. Return this as answer.`,
    icon: "🔧",
    component: PatternRecognition,
    tags: ["Logic Game", "Puzzle"],
    password: PASSWORD_PatternRecognition,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_PatternRecognition,
  },
  {
    path: TASK_ID_StudentProgressChart,
    title: "Student Progress Chart",
    description: `Perform the instructions described at the top of the page to reveal the hidden password. Return the revealed password upon completion.`,
    icon: "📝",
    component: StudentProgressChart,
    tags: ["E-learning", "Progress Chart"],
    password: PASSWORD_StudentProgressChart,
    difficulty: "medium",
    variant: "base",
    base_task: TASK_ID_StudentProgressChart,
  },
];
